#!/usr/bin/env bash
# * baka (v 0.2.0) completion script.

_baka_get_entries() {
    # Collect entries list from /etc/baka/entries

    baka_entries=/etc/baka/entries

    # This is just baka bk_find_entries() function copy-paste.

    local all_files="$(find "$baka_entries" -type f)"

    for file in $all_files; do
        # Resolve symlinks.
        if [ -L "$file" ]; then
            s="$(readlink "$file")"
            if [ -f "$s" ]; then
                file="$s"
            fi
        fi
        # Collect all entries, except ignored if set.
        if [[ ! "${ignore[@]}" =~ "$(basename $file)" ]]; then
            all_entries+=("${file##*/}")
        fi
    done

    echo "${all_entries[@]}"
}

_baka() {
    local cur prev
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    case ${COMP_CWORD} in
        1|3)
            # Firs level commands.
            COMPREPLY=($(compgen -W \
                "help --help --version -c --config
                backup list remove" -- ${cur}))
            ;;
        2|4)
            # Subcommands.
            case ${prev} in
                backup)
                    COMPREPLY=($(compgen -W \
                        "help --help -i --ignore -e --entry
                        --local --no-verify --dry-run --remove" -- ${cur}))
                    ;;
                list)
                    COMPREPLY=($(compgen -W \
                        "help --help -v --verbose" -- ${cur}))
                    ;;
                remove)
                    COMPREPLY=($(compgen -W \
                        "help --help -f --force -l --list" -- ${cur}))
                    ;;
                -c|--config|--config=)
                    compopt -o default; COMPREPLY=()
                    ;;
                *) COMPREPLY=()
                    ;;
            esac
            ;;
        *)
            # Subcommand options completion.
            case ${COMP_WORDS[2]} in
                -i|--ignore|--ignore=|-e|--entry|--entry=)
                    entries_list="$(_baka_get_entries)"
                    COMPREPLY=($(compgen -W \
                        "$entries_list" -- ${cur}))
                    ;;
                *)
                    COMPREPLY=()
                    ;;
            esac
            ;;
    *)
        COMPREPLY=()
        ;;
    esac
}

complete -F _baka baka ./baka
